/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigbang_BigBangCore_Builder */

#ifndef _Included_com_bigbang_BigBangCore_Builder
#define _Included_com_bigbang_BigBangCore_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
