name: C/C++ CI

on:
  push:
    branches:
    - master
    - fix-ci
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: installdep
      run: sudo apt install cmake libsodium-dev
    - name: initProject
      run: git clone https://github.com/bigbangcore/OffLineSignLib.git
    - name: lstest0
      run: pwd && ls
    - name: cdLib
      run: cd OffLineSignLib && pwd && ls
    - name: cmakegen
      run: pwd && ls && cmake .
    - name: maketest
      run: make && ./test_lib
