name: C/C++ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: installdep
      run: sudo apt install git cmake libsodium-dev
    - name: initproject
      run: git clone https://github.com/bigbangcore/OffLineSignLib.git && cd OffLineSignLib
    - name: makebuild
      run: mkdir build && cd build
    - name: cmakegen
      run: cd build && cmake ../
    - name: maketest
      run: cd build && make && ./test_lib
