name: C/C++ CI

on:
  push:
    branches:
    - master
    - fix-ci
  pull_request:


jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: installdep
      run: sudo apt install cmake libsodium-dev
    - name: initProject
      run: cd /home/runner/work/OffLineSignLib && git clone https://github.com/bigbangcore/OffLineSignLib.git
    - name: buildProject
      run: cd /home/runner/work/OffLineSignLib/OffLineSignLib && cmake . && make
    - name: testProject
      run: cd /home/runner/work/OffLineSignLib/OffLineSignLib && ./test_lib
