name: C/C++ CI

on:
  push:
    branches:
    - master
    - fix-ci
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: installdep
      run: sudo apt install cmake libsodium-dev
    - name: cmakegen
      run: ls && cmake .
    - name: maketest
      run: make && ./test_lib
